import { Config } from '@stencil/core';
import { sass } from '@stencil/sass';
import { reactOutputTarget as react } from '@stencil/react-output-target';

export const config: Config = {
  globalScript: 'src/global/app.ts',
  namespace: 'ui-core',
  outputTargets: [
    {
      type: 'dist',
      esmLoaderPath: '../loader',
    },
    {
      type: 'dist-custom-elements',
    },
    {
      type: 'docs-readme',
    },
    {
      type: 'www',
      serviceWorker: null, // disable service workers
    },
    react({
      componentCorePackage: '../../../../ui-core',
      proxiesFile: '../react/src/components/ui-core-react/index.ts',
      includeDefineCustomElements: true,
      excludeComponents: [
        'ion-accordion',
        'ion-accordion-group',
        'ion-avatar',
        'ion-backdrop',
        'ion-badge',
        'ion-breadcrumbs',
        'ion-buttons',
        'ion-card-content',
        'ion-card-header',
        'ion-card-subtitle',
        'ion-card-title',
        'ion-checkbox',
        'ion-chip',
        'ion-col',
        'ion-content',
        'ion-datetime',
        'ion-fab',
        'ion-fab-list',
        'ion-footer',
        'ion-grid',
        'ion-header',
        'ion-img',
        'ion-infinite-scroll',
        'ion-infinite-scroll-content',
        'ion-input',
        'ion-item-divider',
        'ion-item-group',
        'ion-item-options',
        'ion-item-sliding',
        'ion-label',
        'ion-list',
        'ion-list-header',
        'ion-menu',
        'ion-menu-button',
        'ion-menu-toggle',
        'ion-nav',
        'ion-nav-link',
        'ion-note',
        'ion-picker-column',
        'ion-picker-column-internal',
        'ion-picker-internal',
        'ion-progress-bar',
        'ion-radio',
        'ion-radio-group',
        'ion-range',
        'ion-refresher',
        'ion-refresher-content',
        'ion-reorder',
        'ion-reorder-group',
        'ion-ripple-effect',
        'ion-row',
        'ion-searchbar',
        'ion-segment',
        'ion-segment-button',
        'ion-select',
        'ion-select-option',
        'ion-select-popover',
        'ion-skeleton-text',
        'ion-slide',
        'ion-slides',
        'ion-spinner',
        'ion-split-pane',
        'ion-tab',
        'ion-text',
        'ion-textarea',
        'ion-thumbnail',
        'ion-title',
        'ion-toggle',
        'ion-toolbar',
        'ion-virtual-scroll',

        // Routing
        'ion-router',
        'ion-route',
        'ion-route-redirect',
        'ion-router-link',
        'ion-router-outlet',
        'ion-back-button',
        'ion-breadcrumb',
        'ion-tab-button',
        'ion-tabs',
        'ion-tab-bar',
        'ion-button',
        'ion-card',
        'ion-fab-button',
        'ion-item',
        'ion-item-option',

        // Overlays
        'ion-action-sheet',
        'ion-alert',
        'ion-loading',
        'ion-modal',
        'ion-picker',
        'ion-popover',
        'ion-toast',

        'ion-app',
        'ion-icon'
      ]
    }),
  ],
  plugins: [sass()],
};
