/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { Color, Shape } from "./components/globals";
export namespace Components {
    interface IonicButton {
    }
    interface MyButton {
        "color"?: Color;
        "disabled"?: boolean;
        "elevation"?: boolean;
        "shape"?: Shape;
        "size"?: 'large' | 'medium' | 'small';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first": string;
        /**
          * The last name
         */
        "last": string;
        /**
          * The middle name
         */
        "middle": string;
    }
}
declare global {
    interface HTMLIonicButtonElement extends Components.IonicButton, HTMLStencilElement {
    }
    var HTMLIonicButtonElement: {
        prototype: HTMLIonicButtonElement;
        new (): HTMLIonicButtonElement;
    };
    interface HTMLMyButtonElement extends Components.MyButton, HTMLStencilElement {
    }
    var HTMLMyButtonElement: {
        prototype: HTMLMyButtonElement;
        new (): HTMLMyButtonElement;
    };
    interface HTMLMyComponentElement extends Components.MyComponent, HTMLStencilElement {
    }
    var HTMLMyComponentElement: {
        prototype: HTMLMyComponentElement;
        new (): HTMLMyComponentElement;
    };
    interface HTMLElementTagNameMap {
        "ionic-button": HTMLIonicButtonElement;
        "my-button": HTMLMyButtonElement;
        "my-component": HTMLMyComponentElement;
    }
}
declare namespace LocalJSX {
    interface IonicButton {
    }
    interface MyButton {
        "color"?: Color;
        "disabled"?: boolean;
        "elevation"?: boolean;
        "shape"?: Shape;
        "size"?: 'large' | 'medium' | 'small';
    }
    interface MyComponent {
        /**
          * The first name
         */
        "first"?: string;
        /**
          * The last name
         */
        "last"?: string;
        /**
          * The middle name
         */
        "middle"?: string;
    }
    interface IntrinsicElements {
        "ionic-button": IonicButton;
        "my-button": MyButton;
        "my-component": MyComponent;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "ionic-button": LocalJSX.IonicButton & JSXBase.HTMLAttributes<HTMLIonicButtonElement>;
            "my-button": LocalJSX.MyButton & JSXBase.HTMLAttributes<HTMLMyButtonElement>;
            "my-component": LocalJSX.MyComponent & JSXBase.HTMLAttributes<HTMLMyComponentElement>;
        }
    }
}
